<?php
/**
 *Gefferey Zhang
 *lightbox
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body id="indexBody">

	<?php echo $this->getChildHtml('header') ?>
	
	<div id="mainNav" class="widget w-mainNav">
		
		<div class="allCates navSp">
			<dl>
				<dt>
					<a class="linkAllCate" href="http://www.lightinthebox.com/see-all.html">所有商品分类 </a>
				</dt>
			</dl>
			
			<dd id="litb-cate-menu" class="litb-cate-menu ctrInfo ctrTrackA" style="display:block;" page="index" ctr="{area:'category_menu'}">
			
			</dd>
		</div>
			
		<div class="mainSearch navSp">
				
			<?php echo $this->getChildHtml('topSearch'); ?>
				
			<div id="uniYourCart" class="navSp">
				<dl id="cartContainer" class="js_toggleCart cartWidth">
					<dt id="cartInfo" class="navSp">
						<a class="navSp" href="http://www.lightinthebox.com/index.php?main_page=shopping_cart" rel="nofollow">
							<span id="cartItem" class="navSp">
								<span class="navSp">
									<span id="cartCount">0</span>
									<span id="cartText">Cart</span>
									<i class="navSp"></i>
								</span>
							</span>
						</a>
					</dt>
				</dl>
			</div>
			
		</div>
		
	</div>
	
	<div id="wrapper" class="widget">
	
		<div id="wrapper-l">
		
		</div>
		
		<div id="wrapper-r">
		
		</div>
	
	</div>
	
</body>
</html>
