<?php
/**
 *Gefferey Zhang
 *lightbox
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body id="indexBody">

	<?php echo $this->getChildHtml('header') ?>
	
	<div id="wrapper" class="widget">
	
		<div id="wrapper-l">
			<?php echo $this->getChildHtml('left') ?>
		</div>
		
		<div id="wrapper-r">
		
			<!-- ads -->
			<div id="dfp-home-slim">
			
				<div id="IDX_MAIN_TOP_BANNER">
				
					<section class="widget-dfp widget">
					
					</section>
				
				</div>
			
			</div>
			<?php echo $this->getChildHtml('content') ?>
		
		</div>
	
	</div>
	
</body>
</html>
