<div id="searchWrap" class="navSp">
<?php ?>
	<div id="searchWrapInner" class="navSp">
		
		<form id="search_mini_form" class="navSp" target="_parent" method="get" action="/catalogsearch/result/" name="search_mini_form">
		
		
			<input id="q" class="searchArea" type="text" lang="1" autocomplete="off" maxlength="120" value="" dvalue=""  name="q">
		
			<p class="searchBtnWrap">
				<button class="searchBtn navSp" type="submit">
				<span class="ir">Search</span>
				</button>
			</p>
			
		</form>
		
	</div>

</div>