<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<div class="container">
	<div class="pull-left litb-span24">
		 <?php echo $this->getChildHtml('media') ?>
	</div>
	
	<div class="pull-right litb-span36">
		<div class="pagelet product-info clearfix">
		
			<div class="widget prod-info-title">
				<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
			</div>
			
			<div class="widget prod-info-review">
				<?php echo $this->getReviewsSummaryHtml($_product, 'short', true)?>
			</div>
			
			<div class="widget prod-info-price">
				<?php echo $_product -> getFormatedPrice() ?>
			</div>
			
			<form action="<?php echo $this->getSubmitUrl($_product) ?>" class="widget product-addtocart-form" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        		<div class="no-display">
            		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
           			<input type="hidden" name="related_product" id="related-products-field" value="" />
        		</div>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                </div>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>
            
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
        		
        	</form>
		</div>
	</div>
</div>

<div class="container">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
