<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    
    <div class="cart-empty">
    	<div class="message">
    		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    		<?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    		<ul>
    			<li><?php echo $this->__('You have no items in your shopping cart.') ?></li>
    			<li><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></li>
    		</ul>
    		<?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
    	</div>
	</div>
</div>
