<?php 
/*
 * nav menu
 */

?>
<div id="mainNav" class="widget w-mainNav">

<div class="allCates navSp">
	<dl>
		<dt><a class="linkAllCate"
			href="http://www.lightinthebox.com/see-all.html">所有商品分类 </a>
		</dt>
		<dd id="litb-cate-menu" class="litb-cate-menu ctrInfo ctrTrackA"
			style="display: block;" page="index" ctr="{area:'category_menu'}">
		
			<div id="cate-menu" class="cate-menu" style="height: 307px; width: 238px; display: block; z-index: 0; overflow: hidden;">
		
			<?php $_categories = $this->getStoreCategories() ?>
			
			<?php if(count($_categories)): ?>
			
			<?php
				$m = 0; 
				foreach ($_categories as $_category) {
					
					print '<div class="cate-menu-out" style="width: 990px;">';
					
					print '<h2>';
					
					print '<a href="'. $this-> getCategoryUrl ($_category). '">';
					print $_category->getName();
					print '<em></em>';
					print '</a>';
					
					print '</h2>';
					
					//child categories;
					
					$childCats = $_category -> getChildren();
					
					print '<div class="cate-menu-in" style="width: 750px; top: -'.($m * 28 ).'px; display:none; z-index: 50;">';
					
					print '<div class="cate-menu-sub">';
					foreach ($childCats as $childCat) {

						print '<dl>';
						
						print '<dt>';
						
						print '<h3>';
						print '<a href="'. $this-> getCategoryUrl ($childCat). '">';
						print $childCat ->getName();
						print '<em style="display:none;"></em>';
						print '</a>';
						print '</h3>';
						
						print '</dt>';
						
						print '</dl>';

					}
					print '</div>';
					print '</div>';
					
					print '</div>';
					
					$m ++;
				}
			
			?>
			
			<?php endif;?>
			
			</div>
		
		</dd>
	</dl>
</div>

	<div class="mainSearch navSp">
	
		<?php echo $this->getChildHtml('topSearch'); ?>
		
		<div id="uniYourCart" class="navSp">
				<dl id="cartContainer" class="js_toggleCart cartWidth">
					<dt id="cartInfo" class="navSp">
						<a class="navSp" href="http://www.lightinthebox.com/index.php?main_page=shopping_cart" rel="nofollow">
							<span id="cartItem" class="navSp">
								<span class="navSp">
									<span id="cartCount">0</span>
									<span id="cartText">Cart</span>
									<i class="navSp"></i>
								</span>
							</span>
						</a>
					</dt>
				</dl>
			</div>
	</div>

</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl ('js/cat-menu.js'); ?>"></script>