<?php 
/*
 * nav menu
 */

?>


<div class="allCates navSp">
	<dl>
		<dt><a class="linkAllCate"
			href="http://www.lightinthebox.com/see-all.html">所有商品分类 </a></dt>
	</dl>

	<dd id="litb-cate-menu" class="litb-cate-menu ctrInfo ctrTrackA"
		style="display: block;" page="index" ctr="{area:'category_menu'}">
		
		<div id="cate-menu" class="cate-menu" style="height: 307px; width: 238px; display: block; z-index: 0; overflow: hidden;">
		
			<?php $_categories = $this->getStoreCategories() ?>
			
			<?php if(count($_categories)): ?>
			
			<?php 
			
				foreach ($_categories as $_category) {
					var_dump($_category);
				}
			
			?>
			
			<?php endif;?>
			
		</div>
		
	</dd>
</div>