<div id="dfp-home-slides" class="widget">

	<section class="widget-dfp widget">

		<div id="slider">
			<div class="slidercontrolwr">

				<div class="slidercontrol">
				
					<a title="Slide 1" href="#section1">1</a>
					<a title="Slide 1" href="#section2">1</a>
					<a title="Slide 1" href="#section3">1</a>
					<a title="Slide 1" href="#section4">1</a>
				
				</div>

			</div>

			<div class="scroller">
				<div class="content">
					
					<div id="section1">
						
						<a href="#">
						
							<img alt="" src="http://cloud.lbox.me/images/dfp/201308/LITB_c1180_59416_f1_en.jpg?96">
						
						</a>
						
					</div>
					
					<div id="section2">
						
						<a href="#">
						
							<img alt="" src="http://cloud.lbox.me/images/dfp/201307/LITB_60848_home_f4_en.jpg?98">
						
						</a>
						
					</div>
					
					<div id="section3">
						
						<a href="#">
						
							<img alt="" src="http://cloud.lbox.me/images/dfp/201308/LITB_c206_61401_f3_en.jpg?47">
						
						</a>
						
					</div>
					
					<div id="section4">
						
						<a href="#">
						
							<img alt="" src="http://cloud.lbox.me/images/dfp/201308/LITB_c5426_61410_f2_en.jpg?6">
						
						</a>
						
					</div>
					
				</div>
			</div>
			
			
		</div>

	</section>

</div>

<script type="text/javascript">// <![CDATA[
var my_glider = new Glider('slider', {duration:0.5, autoGlide: true, frequency: 4, initialSection: 'section1'});
// ]]></script> 