<div id="uni-header" class="widget w-uniHeader">
<h1><a id="logo" title="Lightinthebox.com"
	href="http://www.lightinthebox.com"> <img width="150" height="46"
	alt="Lightinthebox"
	src="http://www.lightinthebox.com/includes/templates/dev_v2/css/images/sprite/logo.png">
<span>首页</span> </a></h1>
</div>
<div id="mainNav" class="widget w-mainNav">
	<div class="allCates navSp">
		<dl>
			<dt>
				<a class="linkAllCate"
					href="http://www.lightinthebox.com/see-all.html">所有商品分类 </a>
			</dt>
			
			<dd id="litb-cate-menu" class="litb-cate-menu ctrInfo ctrTrackA"
				style="display: block;" page="index" ctr="{area:'category_menu'}">
				
				<div id="cate-menu" class="cate-menu" style="height: 307px; width: 238px; display: block; z-index: 0; overflow: hidden;">
				
					<?php echo $this->getChildHtml('topMenu') ?>
					
				</div>
				
			</dd>
		</dl>
	</div>
	
		<div class="mainSearch navSp">
	
		<?php echo $this->getChildHtml('topSearch'); ?>
		
			<div id="uniYourCart" class="navSp">
				<dl id="cartContainer" class="js_toggleCart cartWidth">
					<dt id="cartInfo" class="navSp">
						<a class="navSp" href="http://www.lightinthebox.com/index.php?main_page=shopping_cart" rel="nofollow">
							<span id="cartItem" class="navSp">
								<span class="navSp">
									<span id="cartCount">0</span>
									<span id="cartText">Cart</span>
									<i class="navSp"></i>
								</span>
							</span>
						</a>
					</dt>
				</dl>
			</div>
		</div>
</div>

<script type="text/javascript" src="<?php echo $this->getSkinUrl ('js/cat-menu.js'); ?>"></script>


