<?php

?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
	
	<div class="order-quantity">
		<label for="quantity"><?php echo $this->__('数量:') ?></label>
	</div>
	
	<div>
		<div class="order-actions">
			<input class="litb-btn add-to-cart-pending" type="submit" value="<?php echo $buttonTitle ?>">
		</div>
		
	</div>
<?php endif; ?>
