<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="widget magnify">
		<img class="imgPreview" alt="" data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'image');?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(384);?>" title="" />
</div>
<script type="text/javascript">

$j(function(){  
    $j('.imgPreview').elevateZoom({
    	zoomWindowWidth:589,
        zoomWindowHeight:383,
        borderSize:1,
        borderColour:'#AAAAAA',
        zoomWindowOffetx:10,
    	zoomWindowOffety:10
    }); 
});  
</script>