<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="">
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image');?>" class="previewImg">
		<img alt="" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(384);?>" title="" />
	</a>
</div>
<script type="text/javascript">

$j(function(){  
    $j('.previewImg').jqzoom();  
});  
</script>