<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="widget magnify">
<?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
?>
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image');?>" class="previewImg">
		<img alt="" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(384);?>" title="" />
	</a>
</div>
<script type="text/javascript">

$j(function(){  
    $j('.previewImg').jqzoom();  
});  
</script>